- name: Install nginx
  ansible.builtin.yum:
    name: nginx
    state: installed
  register: out

- name: removing old nginx documents
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent
