- name: install python
  ansible.builtin.yum:
    name:
      - python36
      - gcc
      - python3-devel
    state: installed

- name: app prereq
  ansible.builtin.include_tasks: "app-prereq.yml"

- name: download python depedencies
  ansible.builtin.pip:
    requirements: /app/requirements.txt
    executable: pip3.6

- name: systemD setup
  ansible.builtin.include_tasks: "systemd.yml"

- name: load schema
  ansible.builtin.include_tasks: "{{schema_type}}-schema.yml"
  when: schema_load